tickers = {
    'Apple': 'AAPL',
    'AMD': 'AMD',
    'Amazon': 'AMZN',
    'Bayer': 'BAYN.DE',
    'Booking.com': 'BKNG',
    'Google': 'GOOG',
    'Eli Lilly': 'LLY',
    'Meta': 'META',
    'MicroStrategy': 'MSTR',
    'Novartis': 'NOVN.SW',
    'Netflix': 'NFLX',
    'NVIDIA': 'NVDA',
    'Palantir': 'PLTR',
    'Qualcomm': 'QCOM',
    'Roche': 'ROG.SW',
    'SAP': 'SAP',
    'Snowflake': 'SNOW',
}
