version: 2

models:
  - name: my_first_dbt_model
    columns:
      - name: today
        tests:
          - not_null
      - name: message
        tests:
          - not_null
          - accepted_values:
              values: ['Hello, dbt + Snowflake!']
